### ISSUE TITLE
Add support for expression aliases

### ISSUE THREAD

**Issue by lerebear** [lerebear/sizeup-core#10]
At present, users are forced to write out scoring formulas without any way to store intermediate values in a variable or alias. This isn't too bad at the moment, but if #9 lands, then I think this will quickly become unwieldy.

To help reusing certain expressions easier, we should support expression aliases that can be used in a formula. That might look like this:

```yaml
scoring:
  aliases:
    changed: + additions deletions
    discounted: + comments whitespace tests
  formula: - changed discounted
```
