### ISSUE TITLE
Aliases can cause an infinite loop in formula evaluation

### ISSUE THREAD

**Issue by lerebear** [lerebear/sizeup-core#51]
The initial implementation for #10 did not include a check for circular references. As a result, an scoring configuration like the one below will result in an infinite loop:

```yaml
scoring:
  formula: foo
  aliases:
    foo: bar
    bar: foo
```

We should fix this by checking for circular references and failing with a definite error.
